#[Config.1] AWS Config should be enabled, for region Canada
policies:
  - name: config-compliance
    resource: account
    region: ca-central-1
    filters:
      - type: check-config
        all-resources: true
        global-resources: true
        running: true
