# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo pip3 install --upgrade pip
          export PATH="/home/vsts/.local/bin:$PATH"
          pip3 install awscli --upgrade 
          pip install c7n --upgrade
          export AWS_ACCESS_KEY_ID="ASIAXDJUAQB3GG2YCOH5" 
          export AWS_SECRET_ACCESS_KEY="9idUzxS1p7XKba8y60tFr2IETQ9wGNcAHnyk64WY" 
          export AWS_SESSION_TOKEN="FwoGZXIvYXdzECYaDEjENAHbEpNRCFyjfCLtAS+e2E6HukFDqugRdsGRax7vOAQROyRjJYCjDjOS6BKh5xA6ueuey69UwWY9h72N97DNoSBJzpUEm6hMN0etLXe5i9TqwMzdDHIFwCfgqvTCYZMiIyiisw63PWgk8n/D3FlhVVFrdmDAfP88brL9d/OUjFcbHLTV4C9EljnuWnBaqJRLSMM/5M53UlKIAwcG/0clVdeMx9KOa4ocpqj+JE0YA9jHkHhnWk3y3tCgg3MVRC7BIrsiUALe9Mz4KQzGB5KRS+wTPYKDHqYXcHrf3P6cotf+37iCsbKopTecG7+Lg47/9At5uwDwavLMhCib/M6CBjIyUxuQecHlIIwo+ySuS/GLjc+otPuKVarAA+IYwhQv5VmdFioFS2PbM0w8vTqZ2T2ZGzM=" 
          export AWS_DEFAULT_REGION=ca-central-1 
          custodian run --dryrun -s policy.yml
          echo Add other actions to build,
          echo test, and deploy your project.
          
