# This is a basic workflow to help you get started with Actions

name: runAcrossAccounts

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #schedule:
  #- cron: '0 14 * * *'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell to install awscli and c7n
      - name: Run script to install awscli and custodian
        run: |
          sudo pip3 install --upgrade pip
          export PATH="/home/vsts/.local/bin:$PATH"
          pip3 install awscli --upgrade
          pip install c7n-org --upgrade

      # Picksup Creds from Secrets set on github
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: github-action
          role-skip-session-tagging: true

      # Run a script to generate config file required for c7n-org, accounts.yml
      # Alternatively, you can create this manually. see https://cloudcustodian.io/docs/tools/c7n-org.html
      - name: Run script to get script and generate config file
        run: |
          cd policy
          wget https://raw.githubusercontent.com/cloud-custodian/cloud-custodian/master/tools/c7n_org/scripts/orgaccounts.py
          python3 orgaccounts.py -f accounts.yml \
            --role 'arn:aws:iam::{Id}:role/CloudCustodian'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Run all policies across accounts
      - name: Across accounts run ALL custodian policies in policy folder
        run: |
          set +x
          export PATH="/home/runner/.local/bin:$PATH"
          cd policy
          while read fileName; do 
             if [[ ${fileName} == *yml ]]; then
               echo Running Policy for file $fileName ; 
               c7n-org run -c accounts.yml -s output -u $filename --dryrun || continue
             fi
          done < <(find . -type f)
