# This is a base workflow to help you get started and run a custodian command.
name: CI_runMugc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ cicd ]
  #pull_request:
  #  branches: [ cicd ]
  #schedule:
  #  - cron: '0 14 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Picksup Creds from Secrets set on github
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: startup-sample-project-github-action
          role-skip-session-tagging: true 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo pip3 install --upgrade pip
          export PATH="/home/vsts/.local/bin:$PATH"
          pip3 install awscli --upgrade 
          pip install c7n --upgrade
          export PATH="/home/runner/.local/bin:$PATH"
          git clone https://github.com/cloud-custodian/cloud-custodian.git
          echo __________________________________________________________________
          custodian run --dryrun -s out policy/workload/ec2.yml
          python3 cloud-custodian/tools/ops/mugc.py -c password.yml --dryrun
          echo __________________________________________________________________      
          
